### ISSUE TITLE
[PE-D] Some group/subgroup commands work when on person view

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-1/tp#202]
write-up is incomplete + the info box says all commands require to be in group view, but this is not true for the add group command

![image.png](https://raw.githubusercontent.com/Yttruire/ped/main/files/66e140ca-b2eb-40d3-9d11-38b512101484.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Yttruire/ped#8

**Comment by kaixin-hc** [comment]
duplicate
