### ISSUE TITLE
[PE-D] Unable to create groups with alphanumeric names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-1/tp#203]
UG gives an example of creating groups with alphanumeric names (eg: group 1 /create t:Students), but product does not accept alphanumeric names for groups

![Screenshot 2021-10-29 165733.png](https://raw.githubusercontent.com/mukundrs/ped/main/files/cc5dc7ef-a64b-44d4-9b88-15687509be2c.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: mukundrs/ped#1

**Comment by kaixin-hc** [comment]
Not closing bc this hgihlights the documentation error, which is not highlighted in duplicate #156
