### ISSUE TITLE
[PE-D] Tags cannot be created or tags are not displayed with groups during creation of group

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-1/tp#215]
Documentation states that groups can be created with tags

![image.png](https://raw.githubusercontent.com/mukundrs/ped/main/files/7f388260-5403-4c29-8fa9-71fa67dae3fc.png)

However, tags are not being added to a group in the product.
eg: when inputing g groupa /c t:tag,

![image.png](https://raw.githubusercontent.com/mukundrs/ped/main/files/b0b86664-8afd-455c-a977-eb55b6bb537b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: mukundrs/ped#5

**Comment by HalphasX** [comment]
duplicate with #226
