### ISSUE TITLE
[PE-D] Person in group, not listed in group under person/list. This is due to adding a person to a group before editing their tags.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-1/tp#216]
![image.png](https://raw.githubusercontent.com/michael-lee-sk/ped/main/files/3bb2c258-b77a-41cb-b2ff-93bf520285d1.png)
State 1 (by right, person Alex is in group :testing, by which has a wrong group number already for some reason)

![image.png](https://raw.githubusercontent.com/michael-lee-sk/ped/main/files/c59cee64-4ef4-4bbb-ac8f-4d157fed6733.png) 
State 2 (person 1 /list shows all the people inside group 1. Alex is labelled under group test whereas this is group testing. Alex does not have group testing under his labels/list of groups)

How to cause the bug
1) Person x is added to group test

2) Person x would have group test labelled under his/her name

3) Add tag to person x

4) Person would have group test removed under his/her name

This is the same when u replace tagging with clearing tags

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: michael-lee-sk/ped#16

**Comment by kaixin-hc** [comment]
can you leave us on the same filtered list as before?
1. open a list of persons in group
2. add tags
3. CURRENT BEHAVIOUR: boots us back to person list. DESIRED BEHAVIOUR: leaves us on the list we were on
